apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "main-go"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://github.com/tellbow/Unikernel-on-K8s/raw/main/unikernel/main.img.xz"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
